chore: tup-677 css/django/vite interoperability (#197)
* chore: tup-677 no commented @import statements

* refactor: tup-677 no absolute /static paths in css

Testing:
1. Verify Frontera fonts still load.

* docs: collectstatic " --ignore assets/*/font*.css"

This need for this is to avoid an error introuduced by tup-677.

```log
Post-processing 'ui/assets/generics/fonts.css' failed!

…

ValueError: The file 'ui/assets/generics/fonts/BentonSans-Regular.otf' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x7ffffc9b5280>.
```

* Revert "docs: collectstatic " --ignore assets/*/font*.css""

This reverts commit 6cf9e6fcd60df174223a236d61b42fa1e617afc4.

* fix(utrc): WP-135 support deploy with CMS v3.12